# Generated by Django 4.1.6 on 2023-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Присылать оповещения о новых комментариях?'),
        ),
    ]
